baseURL = "https://alistaircol.netlify.com"
languageCode = "en-us"
title = "alistaircol"
theme = "papercss-hugo-theme"

[menu]
    [[menu.nav]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.nav]]
        name = "Work"
        url = "/work"
        weight = 2
    [[menu.nav]]
        name = "Articles"
        url = "/articles"
        weight = 3
    [[menu.nav]]
        name = "Projects"
        url = "/projects"
        weight = 4
    [[menu.nav]]
        name = "College"
        url = "/college"
        weight = 5
    [[menu.nav]]
        name = "University"
        url = "/university"
        weight = 6
    [[menu.nav]]
        name = "Contact"
        url = "/contact"
        weight = 7

