baseURL: https://ac93.uk
languageCode: en-us
title: alistaircol
theme: alistaircol-papercss

params:
  homeMetaContent: Ally is a full-stack software engineer.
  dateFormat: Jan 2, 2006

menu:
  nav:
  - name: Articles
    url: /articles/
    weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true
