baseURL = "https://ac93.uk"
languageCode = "en-us"
title = "alistaircol"
theme = "papercss-hugo-theme"

[params]
    homeMetaContent = "Ally is a full-stack software engineer."
    # For more date formats see https://gohugo.io/functions/format/
    dateFormat = "Jan 2, 2006"

[menu]
    [[menu.nav]]
        name = "Work"
        url = "/work/"
        weight = 1
    [[menu.nav]]
        name = "Articles"
        url = "/articles/"
        weight = 2
    [[menu.nav]]
        name = "Projects"
        url = "/projects/"
        weight = 3
    [[menu.nav]]
        name = "Education"
        url = "/education/"
        weight = 4
    [[menu.nav]]
        name = "Contact"
        url = "/contact/"
        weight = 5

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
